# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - green-community

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies and build
        run: |
          # Install server dependencies with legacy peer deps to resolve conflicts
          cd Server
          npm install --legacy-peer-deps
          cd ..
          
          # Install client dependencies and build
          cd client
          npm install
          npm run build
          cd ..
          
          # Run tests if available
          cd Server
          npm run test --if-present
          cd ../client
          npm run test --if-present

      - name: Prepare deployment artifacts
        run: |
          # Copy server files as the main application
          cp -r Server/* .
          
          # Create a public directory for serving client build
          mkdir -p public/client
          cp -r client/.next/static public/client/static 2>/dev/null || true
          cp -r client/.next public/client/build 2>/dev/null || true
          cp -r client/public/* public/ 2>/dev/null || true
          
          # Clean up - remove the separate directories
          rm -rf Server client

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'green-community'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_5EED705F0CF647DA97A05F982404CBF7 }}