name: Build and deploy Node.js app to Azure Web App - greencommunity

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies and build
        run: |
          # Install server dependencies with legacy peer deps to resolve conflicts
          cd Server
          npm install --legacy-peer-deps
          cd ..
          
          # Install client dependencies and build
          cd client
          npm install
          npm run build
          cd ..

      - name: Prepare deployment artifacts
        run: |
          # Copy server files as the main application
          cp -r Server/* .
          
          # Create a public directory for serving client build
          mkdir -p public/client
          cp -r client/.next/static public/client/static 2>/dev/null || true
          cp -r client/.next public/client/build 2>/dev/null || true
          cp -r client/public/* public/ 2>/dev/null || true
          
          # Clean up - remove the separate directories
          rm -rf Server client

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_590830FF75664EA1BF5D7DF0E9C1963D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_99406FEA6DE74B5EB356BA1CAD7B1C2D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CBE9DEB1A36B4792AE601A767B1BD1C2 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'greencommunity'
          slot-name: 'Production'
          package: .

          
